### ISSUE TITLE
BAN and Pause keys aren't working. 

### ISSUE THREAD

**Issue by DKryptic** [KeyAuth/KeyAuth-CPP-Example#17]
Me and others around me, are trying to validate the key has been banned, or paused. Neither function works. Inside of the license call or the login call, that success status is always true. According to the API docs, it should return false, and the reason "key is banned".

**Comment by wnelson03** [comment]
You're probably banning the license, instead of the user. Go the users tab, search the username (which is the key if you used license function) and ban there. I've tested doing this and it works 👍 

apologies for the confusion, I'm working to better document KeyAuth in the future. let me know if you need anymore help, otherwise you can close your issue.
