### ISSUE TITLE
help

### ISSUE THREAD

**Issue by barry-mcockiner** [KeyAuth/KeyAuth-CPP-Example#30]
![image](https://user-images.githubusercontent.com/95534062/170836012-e8a6e0e5-2a87-4fbb-94cb-fefd0d6771df.png)
how to fix

**Comment by wnelson03** [comment]
Make sure you've set configuration settings right, here's video showing setup https://www.youtube.com/watch?v=GB4XW_TsHqA

We only help people with issues with default example with no changes. For cases like these where you've added KeyAuth to your code, you need to Google or add your code to KeyAuth example instead of the other way around.
